# Generated by Django 4.0 on 2023-01-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('symbol_no', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=300)),
                ('exam_year', models.DateField(auto_now_add=True)),
                ('reg_date_time', models.DateTimeField(auto_now_add=True)),
                ('answersheet', models.ImageField(upload_to='answersheet')),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('is_checked', models.BooleanField(default=False)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_foreign', to='Ormapi.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percent', models.FloatField()),
                ('solved_que', models.JSONField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verify_symbol', to='Ormapi.candidatedetails')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam', to='Ormapi.exam')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
                ('is_checked', models.BooleanField(default=False)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_FK', to='Ormapi.exam')),
            ],
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='exam_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ormapi.exam'),
        ),
    ]
